-- =============================================
-- Test Users Setup
-- =============================================
-- NOTE: This script does NOT create auth.users entries
-- Supabase Auth manages authentication separately
--
-- To use these test accounts:
-- 1. Deploy this migration to your Supabase project
-- 2. Use Supabase Auth magic links to sign in:
--    - test1@kidshub.dev
--    - test2@kidshub.dev
-- 3. On first sign-in, Supabase will create auth.users entry
-- 4. The handle_new_user() trigger will create user_profile
-- 5. You can then manually link households to the new user IDs
--
-- For development/testing, you can also:
-- 1. Create test users via Supabase Dashboard > Authentication
-- 2. Or use the Supabase API to create test users programmatically
-- =============================================

-- =============================================
-- Manual Test User IDs (for data consistency)
-- =============================================
-- We'll use fixed UUIDs so that other test data scripts
-- can reference these user IDs
--
-- IMPORTANT: After creating auth users via Supabase Auth,
-- you need to update these UUIDs to match the actual
-- auth.users IDs that Supabase generates
-- =============================================

-- Test User 1: Smith Family
-- Email: test1@kidshub.dev
-- UUID: Will be generated by Supabase Auth on first sign-in
-- For this test data, we'll use: 11111111-1111-1111-1111-111111111111

-- Test User 2: Johnson Family
-- Email: test2@kidshub.dev
-- UUID: Will be generated by Supabase Auth on first sign-in
-- For this test data, we'll use: 22222222-2222-2222-2222-222222222222

-- =============================================
-- TEMPORARY: Create test users in auth.users
-- =============================================
-- This is ONLY for local development/testing
-- In production, users sign up via Supabase Auth
--
-- NOTE: This requires superuser privileges and may not work
-- in hosted Supabase. For hosted environments, create users
-- via the Supabase Dashboard or Auth API instead.
-- =============================================

DO $$
BEGIN
  -- Only attempt if running locally or in a development environment
  -- Check if we can insert into auth.users
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'auth' AND table_name = 'users'
  ) THEN

    -- Insert test user 1 (if not exists)
    INSERT INTO auth.users (
      id,
      instance_id,
      email,
      encrypted_password,
      email_confirmed_at,
      created_at,
      updated_at,
      raw_app_meta_data,
      raw_user_meta_data,
      is_super_admin,
      role
    ) VALUES (
      '11111111-1111-1111-1111-111111111111',
      '00000000-0000-0000-0000-000000000000',
      'test1@kidshub.dev',
      crypt('password123', gen_salt('bf')), -- Default password: password123
      NOW(),
      NOW(),
      NOW(),
      '{"provider":"email","providers":["email"]}',
      '{"family_name":"Smith"}',
      false,
      'authenticated'
    )
    ON CONFLICT (id) DO NOTHING;

    -- Insert test user 2 (if not exists)
    INSERT INTO auth.users (
      id,
      instance_id,
      email,
      encrypted_password,
      email_confirmed_at,
      created_at,
      updated_at,
      raw_app_meta_data,
      raw_user_meta_data,
      is_super_admin,
      role
    ) VALUES (
      '22222222-2222-2222-2222-222222222222',
      '00000000-0000-0000-0000-000000000000',
      'test2@kidshub.dev',
      crypt('password123', gen_salt('bf')), -- Default password: password123
      NOW(),
      NOW(),
      NOW(),
      '{"provider":"email","providers":["email"]}',
      '{"family_name":"Johnson"}',
      false,
      'authenticated'
    )
    ON CONFLICT (id) DO NOTHING;

    RAISE NOTICE 'Test users created in auth.users';
  ELSE
    RAISE NOTICE 'auth.users table not accessible - skip user creation';
  END IF;

EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE 'Insufficient privileges to create auth.users - create users via Supabase Dashboard';
  WHEN OTHERS THEN
    RAISE NOTICE 'Could not create test users in auth.users: %', SQLERRM;
END $$;

-- =============================================
-- Create User Profiles
-- =============================================
-- These will be automatically created by the handle_new_user() trigger
-- when users sign in, but we'll ensure they exist for our test users

INSERT INTO user_profiles (id, created_at, updated_at)
VALUES
  ('11111111-1111-1111-1111-111111111111', NOW(), NOW()),
  ('22222222-2222-2222-2222-222222222222', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- =============================================
-- Test User Summary
-- =============================================
--
-- Test User 1: Smith Family
-- - Email: test1@kidshub.dev
-- - Password: password123 (local dev only)
-- - UUID: 11111111-1111-1111-1111-111111111111
-- - Children: Emma (8), Noah (12)
--
-- Test User 2: Johnson Family
-- - Email: test2@kidshub.dev
-- - Password: password123 (local dev only)
-- - UUID: 22222222-2222-2222-2222-222222222222
-- - Children: Olivia (10)
--
-- =============================================
